### ISSUE TITLE
Fix: 마이페이지 버그 수정 외 4건

### ISSUE THREAD

**Issue by Lisiant** [TravelWONpick/TravelWONpick_server#46]
## 어떤 기능인가요?

> 버그 수정

## 작업 상세 내용

- [x] Refactor: createReservation 메서드 내재화
- [x] Feat: Reservation 여정 텍스트 수정
- [x] Fix: MyPageService NPE 오류 대응
- [x] Fix: Redis 분산 락 이중 접근 수정

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

This change refactors the createReservation method in ReservationService, updates the journey text format in Reservation, fixes NPE in MyPageService, and addresses Redis distributed lock double access issue in FlightService.

You can review changes in this commit: https://github.com/lattaai13/TravelWONpick-TravelWONpick_server-46/commit/6ea244ae97447346b3b8abc28beae79c85f679d7.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
